### ISSUE TITLE
open_cube NoCredentialsError: Unable to locate credentials

### ISSUE THREAD

**Issue by tiagoams** [dcs4cop/xcube#412] opened 2021-02-17 18:05 UTC
I see that there is work being done on store framworks, so this is probably a known problem in the bleeding edge code:

```
ds = open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1')
```

Should return a dataset but halts with an error:

I don't have xcube commit but it was pulled today (probably 1447037)
This is working with commit 74e1e81ed4e0b7c69a34f706f28c45545b705d46 ( Mon Sep 7)

```
---------------------------------------------------------------------------
NoCredentialsError                        Traceback (most recent call last)
    [... skipping hidden 1 frame]

<ipython-input-5-61ca7cb4d98f> in <module>
----> 1 ds = open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1', format_name='zarr')

c:\users\kc05\onedrive - cefas\scripts\dcs4cop\xcube\xcube\core\dsio.py in open_cube(input_path, format_name, **kwargs)
     51     """
---> 52     return open_dataset(input_path, format_name=format_name, is_cube=True, **kwargs)
     53 
(...)
c:\users\kc05\anaconda3\envs\xcube\lib\site-packages\botocore\auth.py in add_auth(self, request)
    355     def add_auth(self, request):
    356         if self.credentials is None:
--> 357             raise NoCredentialsError
    358         datetime_now = datetime.datetime.utcnow()
    359         request.context['timestamp'] = datetime_now.strftime(SIGV4_TIMESTAMP)

NoCredentialsError: Unable to locate credentials
```

For another commit () it fails with a different error:
```
commit 3b612dd6a4ded41bece17cb9fb8da365b42f1dc8 (HEAD -> master, origin/master, origin/HEAD)
Merge: 5984a8e 113dcdd
Author: Norman Fomferra <norman.fomferra@brockmann-consult.de>
Date:   Thu Jan 21
```

```
ds = open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1')
---------------------------------------------------------------------------
EmptyDataError                            Traceback (most recent call last)
<ipython-input-4-1a39d2984562> in <module>
----> 1 ds = open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1')

c:\users\tams00\onedrive - cefas\git\xcube\xcube\core\dsio.py in open_cube(input_path, format_name, **kwargs)
     50     :return: xcube dataset
     51     """
---> 52     return open_dataset(input_path, format_name=format_name, is_cube=True, **kwargs)
     53
     54
(...)
~\Anaconda3\envs\xcube\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
   1996         kwds["usecols"] = self.usecols
   1997
-> 1998         self._reader = parsers.TextReader(src, **kwds)
   1999         self.unnamed_cols = self._reader.unnamed_cols
   2000

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

EmptyDataError: No columns to parse from file
```

**Comment by forman** [comment] 2021-03-23 09:52
@tiagoams Still having this issue?

**Comment by tiagoams** [comment] 2021-04-29 12:20
Hi again,

I am not getting the credentials error, but for versions above 0.5.1 I get "ValueError: group not found at path ''" as it it was an empty zarr file. It works for 0.5.1. I have tried with xcube *servers* on 0.5.1 and 0.7.2 with identical results.

```
(xcube) C:\Users\tams00>xcube --version
xcube, version 0.8.0

(xcube) C:\Users\tams00>python -c "import requests;from xcube.core.dsio import open_cube"

(xcube) C:\Users\tams00>python -c "import requests;from xcube.core.dsio import open_cube;open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1',format_name='zarr')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\tams00\onedrive - cefas\git\xcube\xcube\core\dsio.py", line 52, in open_cube
    return open_dataset(input_path, format_name=format_name, is_cube=True, **kwargs)
  File "c:\users\tams00\onedrive - cefas\git\xcube\xcube\core\dsio.py", line 94, in open_dataset
    dataset = dataset_io.read(input_path, **kwargs)
  File "c:\users\tams00\onedrive - cefas\git\xcube\xcube\core\dsio.py", line 434, in read
    return xr.open_zarr(path_or_store, consolidated=consolidated, **kwargs)
  File "C:\Users\tams00\Anaconda3\envs\xcube\lib\site-packages\xarray\backends\zarr.py", line 646, in open_zarr
    consolidated=consolidated,
  File "C:\Users\tams00\Anaconda3\envs\xcube\lib\site-packages\xarray\backends\zarr.py", line 287, in open_group
    zarr_group = zarr.open_group(store, **open_kwargs)
  File "C:\Users\tams00\Anaconda3\envs\xcube\lib\site-packages\zarr\hierarchy.py", line 1146, in open_group
    err_group_not_found(path)
  File "C:\Users\tams00\Anaconda3\envs\xcube\lib\site-packages\zarr\errors.py", line 25, in err_group_not_found
    raise ValueError('group not found at path %r' % path)
ValueError: group not found at path ''
```

```
(xcube) tams00@74PDLQ2:~/onedrive/git/xcube$ git checkout tags/v0.5.1
Previous HEAD position was 597ff3af Ready for 0.8.0 release, added missing scipy >=1.6.0
HEAD is now at 7f9d57ea Update changelog and version number for v0.5.1
```

```
(xcube) C:\Users\tams00>xcube --version
xcube, version 0.5.1

(xcube) C:\Users\tams00>python -c "import requests;from xcube.core.dsio import open_cube;ds=open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1',format_name='zarr');print(ds)"
<xarray.Dataset>
Dimensions:         (bnds: 2, lat: 5632, lon: 10240, time: 1479)
Coordinates:
  * lat             (lat) float64 62.67 62.66 62.66 62.66 ... 48.01 48.0 48.0
    lat_bnds        (lat, bnds) float64 dask.array<chunksize=(5632, 2), meta=np.ndarray>
  * lon             (lon) float64 -16.0 -16.0 -15.99 ... 10.66 10.66 10.67
    lon_bnds        (lon, bnds) float64 dask.array<chunksize=(10240, 2), meta=np.ndarray>
  * time            (time) datetime64[ns] 2017-01-01T09:57:21.976999680 ... 2...
    time_bnds       (time, bnds) datetime64[ns] dask.array<chunksize=(1479, 2), meta=np.ndarray>
Dimensions without coordinates: bnds
Data variables:
    chl_c2rcc       (time, lat, lon) float64 dask.array<chunksize=(1, 1408, 2560), meta=np.ndarray>
    tsm_c2rcc       (time, lat, lon) float64 dask.array<chunksize=(1, 1408, 2560), meta=np.ndarray>
    tur_nechad_665  (time, lat, lon) float64 dask.array<chunksize=(1, 1408, 2560), meta=np.ndarray>
Attributes:
    acknowledgment:             ESA Sentinel-3 OLCI data, EU HIGHROC project
    comment:
    contributor_name:
    contributor_role:
    creator_email:              info@brockmann-consult.de
    creator_name:               Brockmann Consult GmbH
    creator_url:                https://www.brockmann-consult.de
    date_modified:              2020-03-06T14:37:40.273235
    geospatial_lat_max:         62.666666666666664
    geospatial_lat_min:         48.0
    geospatial_lat_resolution:  0.002604166666666666
    geospatial_lat_units:       degrees_north
    geospatial_lon_max:         10.666666666666664
    geospatial_lon_min:         -16.0
    geospatial_lon_resolution:  0.0026041666666666665
    geospatial_lon_units:       degrees_east
    history:                    xcube/reproj-snap-nc
    id:                         dcs4cop-bc-olci-sns-l2c-v1
    institution:                Brockmann Consult GmbH
    keywords:
    license:                    terms and conditions of the DCS4COP data dist...
    naming_authority:           bc
    processing_level:           L2C
    project:                    DCS4COP
    publisher_email:            info@brockmann-consult.de
    publisher_name:             Brockmann Consult GmbH
    publisher_url:              https://www.brockmann-consult.de
    references:                 https://dcs4cop.eu/
    source:                     Sentinel-3 OLCI L2 surface observation
    standard_name_vocabulary:
    summary:
    time_coverage_end:          2017-12-31T11:02:19.460000000
    time_coverage_start:        2017-01-01T09:56:22.860999936
    title:                      DCS4COP Sentinel-3 OLCI L2C Data Cube
```

**Comment by tiagoams** [comment] 2021-04-29 12:27
@forman It breaks when the client is at v0.6.0, unless there has been a change in the /s3bucket API.


```
(xcube) C:\Users\tams00>xcube --version
xcube, version 0.6.0

(xcube) C:\Users\tams00>python -c "import requests;from xcube.core.dsio import open_cube;ds=open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1',format_name='zarr');print(ds)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\tams00\onedrive - cefas\git\xcube\xcube\core\dsio.py", line 52, in open_cube
    return open_dataset(input_path, format_name=format_name, is_cube=True, **kwargs)
  File "c:\users\tams00\onedrive - cefas\git\xcube\xcube\core\dsio.py", line 94, in open_dataset
    dataset = dataset_io.read(input_path, **kwargs)
  File "c:\users\tams00\onedrive - cefas\git\xcube\xcube\core\dsio.py", line 434, in read
    return xr.open_zarr(path_or_store, consolidated=consolidated, **kwargs)
  File "C:\Users\tams00\Anaconda3\envs\xcube\lib\site-packages\xarray\backends\zarr.py", line 646, in open_zarr
    consolidated=consolidated,
  File "C:\Users\tams00\Anaconda3\envs\xcube\lib\site-packages\xarray\backends\zarr.py", line 287, in open_group
    zarr_group = zarr.open_group(store, **open_kwargs)
  File "C:\Users\tams00\Anaconda3\envs\xcube\lib\site-packages\zarr\hierarchy.py", line 1146, in open_group
    err_group_not_found(path)
  File "C:\Users\tams00\Anaconda3\envs\xcube\lib\site-packages\zarr\errors.py", line 25, in err_group_not_found
    raise ValueError('group not found at path %r' % path)
ValueError: group not found at path ''
```

**Comment by tiagoams** [comment] 2021-04-29 13:14
I have deleted the entries above as these were caused by not updating the dependencies. after checkoing out a more modern version of xcube. I have tested this again using conda to install the several versions of xcube package from conda forge and I am getting the original "NoCredentialsError: Unable to locate credentials" error.

Thanks to @kcollingridge for pointing out that this problem persisted and the version of xcube where this still works.

As before, open_cube( /s3bucket) works in 0.5.1 but not for more recent versions of xcube:

```
(xcubeconda) C:\Users\tams00>xcube --version
xcube, version 0.8.0

(xcubeconda) C:\Users\tams00>python -c "import requests;from xcube.core.dsio import open_cube;ds=open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1',format_name='zarr');print(ds)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\xcube\core\dsio.py", line 52, in open_cube
    return open_dataset(input_path, format_name=format_name, is_cube=True, **kwargs)
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\xcube\core\dsio.py", line 94, in open_dataset
    dataset = dataset_io.read(input_path, **kwargs)
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\xcube\core\dsio.py", line 428, in read
    path_or_store, consolidated = get_path_or_s3_store(path_or_store,
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\xcube\core\dsio.py", line 570, in get_path_or_s3_store
    consolidated = mode == "r" and s3.exists(f'{root}/.zmetadata')
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\fsspec\asyn.py", line 72, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\fsspec\asyn.py", line 53, in sync
    raise result[0]
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\fsspec\asyn.py", line 20, in _runner
    result[0] = await coro
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\s3fs\core.py", line 725, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\s3fs\core.py", line 911, in _info
    out = await self._call_s3(
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\s3fs\core.py", line 252, in _call_s3
    raise translate_boto_error(err)
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\s3fs\core.py", line 233, in _call_s3
    out = await method(**additional_kwargs)
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\aiobotocore\client.py", line 140, in _make_api_call
    http, parsed_response = await self._make_request(
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\aiobotocore\client.py", line 160, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\aiobotocore\endpoint.py", line 85, in _send_request
    request = await self.create_request(request_dict, operation_model)
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\aiobotocore\endpoint.py", line 78, in create_request
    await self._event_emitter.emit(event_name, request=request,
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\aiobotocore\hooks.py", line 27, in _emit
    response = await handler(**kwargs)
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\aiobotocore\signers.py", line 16, in handler
    return await self.sign(operation_name, request)
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\aiobotocore\signers.py", line 63, in sign
    auth.add_auth(request)
  File "C:\Users\tams00\Anaconda3\envs\xcubeconda\lib\site-packages\botocore\auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by tiagoams** [comment] 2021-04-29 15:34
And here it is working for 0.5.0. 

```
(xcubeconda) C:\Users\tams00>xcube --version
xcube, version 0.5.0

(xcubeconda) C:\Users\tams00>python -c "from xcube.core.dsio import open_cube;ds=open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1',format_name='zarr');print(ds)"
<xarray.Dataset>
Dimensions:         (bnds: 2, lat: 5632, lon: 10240, time: 1479)
Coordinates:
  * lat             (lat) float64 62.67 62.66 62.66 62.66 ... 48.01 48.0 48.0
    lat_bnds        (lat, bnds) float64 dask.array<chunksize=(5632, 2), meta=np.ndarray>
  * lon             (lon) float64 -16.0 -16.0 -15.99 ... 10.66 10.66 10.67
    lon_bnds        (lon, bnds) float64 dask.array<chunksize=(10240, 2), meta=np.ndarray>
  * time            (time) datetime64[ns] 2017-01-01T09:57:21.976999680 ... 2...
    time_bnds       (time, bnds) datetime64[ns] dask.array<chunksize=(1479, 2), meta=np.ndarray>
Dimensions without coordinates: bnds
Data variables:
    chl_c2rcc       (time, lat, lon) float64 dask.array<chunksize=(1, 1408, 2560), meta=np.ndarray>
    tsm_c2rcc       (time, lat, lon) float64 dask.array<chunksize=(1, 1408, 2560), meta=np.ndarray>
    tur_nechad_665  (time, lat, lon) float64 dask.array<chunksize=(1, 1408, 2560), meta=np.ndarray>
Attributes: (12/34)
    acknowledgment:             ESA Sentinel-3 OLCI data, EU HIGHROC project
    comment:
    contributor_name:
    contributor_role:
    creator_email:              info@brockmann-consult.de
    creator_name:               Brockmann Consult GmbH
    ...                         ...
    source:                     Sentinel-3 OLCI L2 surface observation
    standard_name_vocabulary:
    summary:
    time_coverage_end:          2017-12-31T11:02:19.460000000
    time_coverage_start:        2017-01-01T09:56:22.860999936
    title:                      DCS4COP Sentinel-3 OLCI L2C Data Cube

(xcubeconda) C:\Users\tams00>
```

**Comment by AliceBalfanz** [comment] 2021-05-06 14:48
Hi @tiagoams , I cannot reproduce the issue - but there is a difference how I request the data: 

`ds = open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1', format_name='zarr')`

Could you please check, if this solves the problem? Cheers :) 

xcube version 0.8.0

**Comment by tiagoams** [comment] 2021-06-23 16:22
@AliceBalfanz I am getting the same error with xcube 0.8.1 installed from conda-forge on Linux and Windows. I have no idea why we are getting different results.

```
>>> from xcube.core.dsio import open_cube
>>> ds = open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1', format_name='zarr')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/xcube/core/dsio.py", line 52, in open_cube
    return open_dataset(input_path, format_name=format_name, is_cube=True, **kwargs)
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/xcube/core/dsio.py", line 94, in open_dataset
    dataset = dataset_io.read(input_path, **kwargs)
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/xcube/core/dsio.py", line 428, in read
    path_or_store, consolidated = get_path_or_s3_store(path_or_store,
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/xcube/core/dsio.py", line 570, in get_path_or_s3_store
    consolidated = mode == "r" and s3.exists(f'{root}/.zmetadata')
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/fsspec/asyn.py", line 121, in wrapper
    return maybe_sync(func, self, *args, **kwargs)
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/fsspec/asyn.py", line 100, in maybe_sync
    return sync(loop, func, *args, **kwargs)
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/fsspec/asyn.py", line 71, in sync
    raise exc.with_traceback(tb)
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/fsspec/asyn.py", line 55, in f
    result[0] = await future
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/s3fs/core.py", line 692, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/s3fs/core.py", line 857, in _info
    out = await self._call_s3(
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/s3fs/core.py", line 252, in _call_s3
    raise translate_boto_error(err) from err
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/s3fs/core.py", line 234, in _call_s3
    return await method(**additional_kwargs)
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/aiobotocore/client.py", line 140, in _make_api_call
    http, parsed_response = await self._make_request(
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/aiobotocore/client.py", line 160, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 85, in _send_request
    request = await self.create_request(request_dict, operation_model)
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 78, in create_request
    await self._event_emitter.emit(event_name, request=request,
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/aiobotocore/hooks.py", line 27, in _emit
    response = await handler(**kwargs)
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/aiobotocore/signers.py", line 16, in handler
    return await self.sign(operation_name, request)
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/aiobotocore/signers.py", line 63, in sign
    auth.add_auth(request)
  File "/home/cefas-admin/anaconda3/envs/xcube.0.8.1/lib/python3.9/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
>>> ds = open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1', format_name='zarr')
```

BTW there is an issue with s3spec not keeping up with changes in fsspec that is breaking xcube server 0.8.1. I am correcting this by forcing installation of fsspec=0.8.7.
https://github.com/dask/s3fs/issues/465

**Comment by AliceBalfanz** [comment] 2021-07-08 09:30
Hi @tiagoams 

yes, it seems that fsspec and aiobotocore are causing the issues. 

So I took the most recent xcube from master and had to install manually (mamba is the faster conda, you can install it with `conda install mamba -c conda-forge` or replace mamba with conda:

mamba install aiobotocore=1.2.2 -c conda-forge
mamba install fsspec=0.9.0 -c conda-forge

Then it works for me. This is only a quick fix - we need to ensure our xcube env is working correctly without any installation changes afterwards. 

Could you confirm if this works for you as well?

**Comment by AliceBalfanz** [comment] 2021-07-08 11:32
@tiagoams it is very mysterious - it only works on my machine. With other machines (both linux and windows) which have the exact same env as on my local machine we get the same error as you reported above.

**Comment by AliceBalfanz** [comment] 2021-07-08 12:01
Now found the source of all evil :) Accessing a cube which is published via xcube serve only works if an .aws directory in exists in the users home directory with credentials (can be made up, I tried with made up credentials). If the .aws directory is not present, the error reported by tiago appears. One needs to specify that the cube is open to anonymous access, which can be specified by adding `s3_kwargs=dict(anon=True)`

`ds = open_cube('http://service.demo.dcs4cop.eu/xcube/api/latest/s3bucket/bc_olci_ns_tirr_v1', format_name='zarr', s3_kwargs=dict(anon=True))`

@forman , is it possible that we extend the error message with the hint that maybe the user needs to add the anon=True bit of code if he/she is trying to access a public cube?

**Comment by AliceBalfanz** [comment] 2021-07-08 12:31
> mamba install aiobotocore=1.2.2 -c conda-forge
> mamba install fsspec=0.9.0 -c conda-forge

This is still relevant though. With the newes aiobotocore and fsspec a different error occurs. we need to check this.

**Comment by forman** [comment] 2021-07-08 13:17
@AliceBalfanz @tiagoams 

> Accessing a cube which is published via xcube serve only works if an .aws directory in exists in the users home directory with credentials (can be made up, I tried with made up credentials). If the .aws directory is not present, the error reported by tiago appears.

In addition to the `.aws/credentials`  settings (created by AWS S3 CLI) you can also spcify environment variables, for example:

```bash
$ export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
$ export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

>  is it possible that we extend the error message with the hint that maybe the user needs to add the anon=True bit of code if he/she is trying to access a public cube?

I opened https://github.com/dcs4cop/xcube/pull/482

**Comment by forman** [comment] 2021-07-09 08:01
@tiagoams can you please try server / client with xcube code + fresh env from master?

**Comment by tiagoams** [comment] 2021-07-12 14:21
This is how I tested:

- git pull to latest commit 
commit a23063db0dfd5c30dce35c64de10b119448d4ded (HEAD -> master, origin/master, origin/HEAD)
- mamba install -f environment.nml
- mamba install aiobotocore=1.2.2 fsspec=0.9.0 -c conda-forge-f environment.nml
- pip install --no-deps --editable .

**Testing on local server:**

    xcube serve -v -c ./examples/serve/demo/config.yml

and

    ds = open_cube('http://localhost:8080/s3bucket/local', format_name='zarr', s3_kwargs=dict(anon=True))

returns:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tams00\OneDrive - CEFAS\git\xcube\xcube\core\dsio.py", line 53, in open_cube
    return open_dataset(input_path, format_name=format_name, is_cube=True, **kwargs)
  File "C:\Users\tams00\OneDrive - CEFAS\git\xcube\xcube\core\dsio.py", line 95, in open_dataset
    dataset = dataset_io.read(input_path, **kwargs)
  File "C:\Users\tams00\OneDrive - CEFAS\git\xcube\xcube\core\dsio.py", line 435, in read
    return xr.open_zarr(path_or_store, consolidated=consolidated, **kwargs)
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\xarray\backends\zarr.py", line 687, in open_zarr
    ds = open_dataset(
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\xarray\backends\api.py", line 496, in open_dataset
    backend_ds = backend.open_dataset(
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\xarray\backends\zarr.py", line 747, in open_dataset
    ds = store_entrypoint.open_dataset(
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\xarray\backends\store.py", line 22, in open_dataset
    vars, attrs = store.load()
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\xarray\backends\common.py", line 124, in load
    (_decode_variable_name(k), v) for k, v in self.get_variables().items()
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\xarray\backends\zarr.py", line 378, in get_variables
    return FrozenDict(
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\xarray\core\utils.py", line 446, in FrozenDict
    return Frozen(dict(*args, **kwargs))
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\xarray\backends\zarr.py", line 378, in <genexpr>
    return FrozenDict(
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\zarr\hierarchy.py", line 482, in _array_iter
    for key in sorted(listdir(self._store, self._path)):
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\zarr\storage.py", line 174, in listdir
    return _listdir_from_keys(store, path)
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\zarr\storage.py", line 156, in _listdir_from_keys
    for key in list(store.keys()):
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\fsspec\mapping.py", line 158, in __len__
    return len(self.fs.find(self.root))
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\fsspec\asyn.py", line 72, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\fsspec\asyn.py", line 53, in sync
    raise result[0]
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\fsspec\asyn.py", line 20, in _runner
    result[0] = await coro
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\s3fs\core.py", line 596, in _find
    self.dircache[par].append(o)
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\fsspec\dircache.py", line 62, in __getitem__
    return self._cache[item]  # maybe raises KeyError
KeyError: 's3bucket'
```
Is this not the url that the local server should be responding to?

**Testing the public server**
```
ds = open_cube(
    's3bucket/bc_olci_ns_tirr_v1', 
    format_name='zarr', 
    s3_kwargs={
        'anon': True
    },
    s3_client_kwargs={
        'endpoint_url': 'http://service.demo.dcs4cop.eu/xcube/api/latest'
    }
)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tams00\OneDrive - CEFAS\git\xcube\xcube\core\dsio.py", line 53, in open_cube
    return open_dataset(input_path, format_name=format_name, is_cube=True, **kwargs)
  File "C:\Users\tams00\OneDrive - CEFAS\git\xcube\xcube\core\dsio.py", line 95, in open_dataset
    dataset = dataset_io.read(input_path, **kwargs)
  File "C:\Users\tams00\OneDrive - CEFAS\git\xcube\xcube\core\dsio.py", line 429, in read
    path_or_store, consolidated = get_path_or_s3_store(path_or_store,
  File "C:\Users\tams00\OneDrive - CEFAS\git\xcube\xcube\core\dsio.py", line 571, in get_path_or_s3_store
    s3, root = parse_s3_fs_and_root(path_or_url,
  File "C:\Users\tams00\OneDrive - CEFAS\git\xcube\xcube\core\dsio.py", line 609, in parse_s3_fs_and_root
    s3 = new_s3_file_system(s3_kwargs=s3_kwargs,
  File "C:\Users\tams00\OneDrive - CEFAS\git\xcube\xcube\core\dsio.py", line 645, in new_s3_file_system
    s3.exists(check_path)
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\fsspec\asyn.py", line 72, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\fsspec\asyn.py", line 53, in sync
    raise result[0]
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\fsspec\asyn.py", line 20, in _runner
    result[0] = await coro
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\s3fs\core.py", line 724, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "C:\Users\tams00\AppData\Local\miniforge3\envs\xcube\lib\site-packages\s3fs\core.py", line 922, in _info
    "Size": out["ContentLength"],
KeyError: 'ContentLength'
```

**Comment by AliceBalfanz** [comment] 2021-07-14 13:27
Hi Tiago, 
I faced the same  KeyError you saw when trying to access the cube from local server. For me it was due to an outdated environment. https://github.com/dcs4cop/xcube/issues/490
could you try again with slightly different installation process: 

-     git pull to latest commit
-     mamba  remove --name xcube --all
-     mamba env create
-     conda activate xcube
-     mamba  install -c conda-forge jupyterlab
-     python setup.py develop

`xcube serve -v -c ./examples/serve/demo/config.yml`

in notebook: 

ds = open_cube('s3bucket/local', format_name='zarr', s3_kwargs=dict(anon=True),  s3_client_kwargs={
        'endpoint_url': 'http://localhost:8080/'})

and this should work as well: 

```
ds = open_cube(
    's3bucket/bc_olci_ns_tirr_v1', 
    format_name='zarr', 
    s3_kwargs={
        'anon': True
    },
    s3_client_kwargs={
        'endpoint_url': 'http://service.demo.dcs4cop.eu/xcube/api/latest'
    }
)
```

**Comment by AliceBalfanz** [comment] 2021-08-11 14:39
Hi Tiago, I will close this issue because I think how everything is clarified, correct? In case you still have problems feel free to reopen the issue :)

**Closed by AliceBalfanz** 2021-08-11 14:39 UTC
