### ISSUE TITLE
`xcube --version` does not correspond to value in version.py

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#749] opened 2022-10-14 09:32 UTC
**Describe the bug**
I have the current master branch checked out and updated, as well as xcube activated and called `python setup.py develop`. 
However, when I call `xcube --version` I get `xcube, version 0.12.1`. Expected version is `0.13.0.dev2`
![image](https://user-images.githubusercontent.com/23457217/195813305-81ae6435-ead0-4328-a4b3-0a9ce0208c96.png)

**Comment by pont-us** [comment] 2022-10-14 15:29
Can't reproduce here; I get `0.13.0.dev2`. Try `which xcube` to check that you're definitely running the xcube that you installed.

**Comment by forman** [comment] 2022-10-28 07:36
I close this, it was an error in @AliceBalfanz's environment, namely xcube was installed as a package plus as a link for development.

**Closed by forman** 2022-10-28 07:36 UTC
