### ISSUE TITLE
xcube gen generates duplicates in time and unsorted time dimension for S2+

### ISSUE THREAD

**Issue by gunbra32** [dcs4cop/xcube#45] opened 2019-04-30 16:01 UTC
**Describe the bug**
xcube gen generates two identical time slices with S2+ plugin. In the input data there is only one input file. In addition, the time dimension is not sorted. 

**To Reproduce**
The cube has been produced in xcube-gen with the the following command. 
nohup xcube gen --append -v CHL_GILERSON2010_GLOBAL,KdPAR,SPM_VITOnir_SCHELDT,TUR_NECHAD2009_GLOBAL_665 -c /home/xcube/projects/xcube-services/dcs4cop/xcube-gen-configs/dcs4cop-gen_BC_config_S2.yml /data/EOdata/related/DCS4COP/cube_input/VITO/2017/*/*.nc > nohup.out &
The resulting zarr file is still on xcube-gen at /home/xcube/xcube-output/ dcs4cop-bc-s2-sns-l2c-v1.zarr
Note that this issue might be related to the fact that the generation has been interrupted and started again with the same output name. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7138923/56975208-97df1700-6b70-11e9-85af-a6fcc7e7caa2.png)

**Comment by forman** [comment] 2019-05-02 11:03
Maybe a duplicate of #33 ?

**Comment by forman** [comment] 2019-05-06 08:54
![](https://github.trello.services/images/mini-trello-icon.png) [Generate S2-Plus data cubes for generic use case](https://trello.com/c/OGLyedMK/2-generate-s2-plus-data-cubes-for-generic-use-case)

**Comment by forman** [comment] 2019-05-06 08:54
![](https://github.trello.services/images/mini-trello-icon.png) [Generate S2-Plus data cubes for generic use case](https://trello.com/c/OGLyedMK/2-generate-s2-plus-data-cubes-for-generic-use-case)

**Comment by forman** [comment] 2019-08-12 09:34
Merged.

**Closed by forman** 2019-08-12 09:34 UTC
Labels: bug, enhancement, important, urgent, xcube gen
