### ISSUE TITLE
Problem with time series for places used in multiple xcubes

### ISSUE THREAD

**Issue by kcollingridge** [dcs4cop/xcube#389] opened 2020-12-17 13:29 UTC
**Describe the bug**
If you add the same geojson file for places under two different datacubes in xcube viewer, the time series function does not work for the second data cube. It will say no data found when you press the time series button despite there clearly being data present. 

**To Reproduce**
1. In the config file for the xcube viewer, add a places file, e.g.:
  - Identifier: smartbuoys
    Title: SmartBuoys
    Path: "places/Smartbuoys.geojson" 
    PropertyMapping:
      label: deployment
2. And load these places for two xcubes, e.g.:
  - Identifier: cmems_oc
    Title: CMEMS Ocean Colour
    Path: /home/kate/datacubes/cmems_oc2.zarr
    Style: default
    PlaceGroups:
      - PlaceGroupRef: smartbuoys
  - Identifier: ostia
    Title: Ostia SST
    Path: /home/kate/datacubes/cmems_ostia_sst.zarr
    Style: default
    PlaceGroups:
     - PlaceGroupRef: smartbuoys
3. Once the view is loaded, go directly to the second data cube (OSTIA SST in this case).
4. Load places and select a place
5. Press the time series button
6. It will display a message at the bottom to say "No data found here."

**Expected behavior**
Timeseries for places to work for all datacubes even if they use the same places file.

**Screenshots**
![image](https://user-images.githubusercontent.com/44020632/102493368-f8370b00-406a-11eb-9ba9-35a412c0102c.png)

**Desktop (for viewer not server):**
 - OS: Windows 10 Enterprise
 - Browser: Edge v87.0.664.60

**Additional context**
 If in the viewer you load the places under the first datacube there is no issue with the time series function, and it will subsequently work for the second data cube. But we cannot expect the user to access the datacubes in order.
 My current workaround is to duplicate the places file and load the duplicate for the second datacube.

**Comment by forman** [comment] 2020-12-23 10:19
Thanks @kcollingridge for reporting. Should be easy to fix (next year). Happy 2021!

**Comment by forman** [comment] 2021-04-28 06:39
@AliceBalfanz have you recently seen similar issues with our configuration?

**Comment by AliceBalfanz** [comment] 2021-07-14 13:56
@forman: I canfirm that the bug exists - in our water services dev viewer we use the same shapefile for lakes and points for Deutschland/SH HR and for Deutschland/SH v7 - there we observe the same 'no data'

**Comment by clebreton** [comment] 2022-03-24 14:27
I would to bring this issue back up. We have that problem with the BIGFE service where here several users access their own cubes and use the same Places geojson file. 
The problem is critical here because users don't get access to the first cube on the cube listing, only their own and as such there is no workaround for this bug.

**Comment by AliceBalfanz** [comment] 2022-04-21 08:32
This problem has been fixed in the most recent release: https://github.com/dcs4cop/xcube/releases/tag/v0.11.0

**Closed by AliceBalfanz** 2022-04-21 08:32 UTC
Labels: bug, xcube serve
