### ISSUE TITLE
`xcube.core.store.new_data_store` fails with pyproj version 3.5.0 

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#853] opened 2023-05-08 09:35 UTC
**Describe the bug**
importing `from xcube.core.store import new_data_store` fails when `pyproj` version is  3.5.0.

xcube version is 1.0.5, when creating an env, where pyproj is restricted to version 3.4.1 the below error does not occur. 
**To Reproduce**
install an env, where pyproj is not restricted 
`from xcube.core.store import new_data_store`
```
---------------------------------------------------------------------------
CRSError                                  Traceback (most recent call last)
Cell In[3], line 1
----> 1 from xcube.core.store import new_data_store


File /home/conda/deepesdl1/bdb65d6252ad5f0cde7afdbe24bb7568f50d9590ef48ee912ee37a33e358cbb5-20230508-091044-634474-133-ml-tensorflow-2/lib/python3.9/site-packages/xcube/core/store/__init__.py:22
      1 # The MIT License (MIT)
      2 # Copyright (c) 2021 by the xcube development team and contributors
      3 #
   (...)
     19 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
     20 # SOFTWARE.
---> 22 from .accessor import DataDeleter
     23 from .accessor import DataOpener
     24 from .accessor import DataTimeSliceUpdater

File /home/conda/deepesdl1/bdb65d6252ad5f0cde7afdbe24bb7568f50d9590ef48ee912ee37a33e358cbb5-20230508-091044-634474-133-ml-tensorflow-2/lib/python3.9/site-packages/xcube/core/store/accessor.py:35
     33 from xcube.util.jsonschema import JsonObjectSchema
     34 from xcube.util.plugin import get_extension_registry
---> 35 from .datatype import DataType
     36 from .datatype import DataTypeLike
     37 from .error import DataStoreError

File /home/conda/deepesdl1/bdb65d6252ad5f0cde7afdbe24bb7568f50d9590ef48ee912ee37a33e358cbb5-20230508-091044-634474-133-ml-tensorflow-2/lib/python3.9/site-packages/xcube/core/store/datatype.py:29
     26 import geopandas
     27 import xarray
---> 29 from xcube.core.mldataset import MultiLevelDataset
     30 from xcube.util.assertions import assert_instance
     31 from xcube.util.jsonschema import JsonStringSchema

File /home/conda/deepesdl1/bdb65d6252ad5f0cde7afdbe24bb7568f50d9590ef48ee912ee37a33e358cbb5-20230508-091044-634474-133-ml-tensorflow-2/lib/python3.9/site-packages/xcube/core/mldataset/__init__.py:23
      1 # The MIT License (MIT)
      2 # Copyright (c) 2023 by the xcube team and contributors
      3 #
   (...)
     19 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
     20 # DEALINGS IN THE SOFTWARE.
---> 23 from .abc import MultiLevelDataset
     24 from .base import BaseMultiLevelDataset
     25 from .combined import CombinedMultiLevelDataset

File /home/conda/deepesdl1/bdb65d6252ad5f0cde7afdbe24bb7568f50d9590ef48ee912ee37a33e358cbb5-20230508-091044-634474-133-ml-tensorflow-2/lib/python3.9/site-packages/xcube/core/mldataset/abc.py:29
     25 from typing import Sequence, Any, Dict, Callable, Tuple
     27 import xarray as xr
---> 29 from xcube.core.gridmapping import GridMapping
     30 from xcube.core.tilingscheme import TilingScheme
     31 from xcube.util.types import ScalarOrPair

File /home/conda/deepesdl1/bdb65d6252ad5f0cde7afdbe24bb7568f50d9590ef48ee912ee37a33e358cbb5-20230508-091044-634474-133-ml-tensorflow-2/lib/python3.9/site-packages/xcube/core/gridmapping/__init__.py:22
      1 # The MIT License (MIT)
      2 # Copyright (c) 2021 by the xcube development team and contributors
      3 #
   (...)
     19 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
     20 # SOFTWARE.
---> 22 from .base import CRS_CRS84
     23 from .base import CRS_WGS84
     24 from .base import DEFAULT_TOLERANCE

File /home/conda/deepesdl1/bdb65d6252ad5f0cde7afdbe24bb7568f50d9590ef48ee912ee37a33e358cbb5-20230508-091044-634474-133-ml-tensorflow-2/lib/python3.9/site-packages/xcube/core/gridmapping/base.py:51
     48 CRS_WGS84 = pyproj.crs.CRS(4326)
     50 # WGS84, axis order: lon, lat
---> 51 CRS_CRS84 = pyproj.crs.CRS.from_string("CRS84")
     53 # Default tolerance for all operations that
     54 # accept a key-word argument "tolerance":
     55 DEFAULT_TOLERANCE = 1.0e-5

File /home/conda/deepesdl1/bdb65d6252ad5f0cde7afdbe24bb7568f50d9590ef48ee912ee37a33e358cbb5-20230508-091044-634474-133-ml-tensorflow-2/lib/python3.9/site-packages/pyproj/crs/crs.py:454, in CRS.from_string(cls, in_crs_string)
    434 @classmethod
    435 def from_string(cls, in_crs_string: str) -> "CRS":
    436     """
    437     Make a CRS from:
    438 
   (...)
    452     CRS
    453     """
--> 454     return cls.from_user_input(_prepare_from_string(in_crs_string))

File /home/conda/deepesdl1/bdb65d6252ad5f0cde7afdbe24bb7568f50d9590ef48ee912ee37a33e358cbb5-20230508-091044-634474-133-ml-tensorflow-2/lib/python3.9/site-packages/pyproj/crs/crs.py:501, in CRS.from_user_input(cls, value, **kwargs)
    499 if isinstance(value, cls):
    500     return value
--> 501 return cls(value, **kwargs)

File /home/conda/deepesdl1/bdb65d6252ad5f0cde7afdbe24bb7568f50d9590ef48ee912ee37a33e358cbb5-20230508-091044-634474-133-ml-tensorflow-2/lib/python3.9/site-packages/pyproj/crs/crs.py:348, in CRS.__init__(self, projparams, **kwargs)
    346     self._local.crs = projparams
    347 else:
--> 348     self._local.crs = _CRS(self.srs)

File pyproj/_crs.pyx:2366, in pyproj._crs._CRS.__init__()
CRSError: Invalid projection: CRS84: (Internal Proj Error: proj_create: unrecognized format / unknown name)
```

**Comment by pont-us** [comment] 2024-02-14 13:30
Closing as duplicate of #869 .

**Closed by pont-us** 2024-02-14 13:30 UTC
Labels: duplicate
